### ISSUE TITLE
Force refreshing shared folders returned error.

### ISSUE THREAD

**Issue by mashedpotats** [Telenav/dropbox-admin#26]
Screenshot:
![image](https://cloud.githubusercontent.com/assets/9442368/21290687/09c598ae-c479-11e6-93f0-01cec2d89294.png)

Error:
```python
127.0.0.1 - - [17/Dec/2016 16:49:20] "GET /shared-folders?force-update=1 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "C:\Python27\lib\site-packages\flask\app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\projects\tnav\dropbox-admin\dbadmin.py", line 31, in list_all_shared_folders
    result = service.list_all_shared_folders(force_update=force_update)
  File "D:\projects\tnav\dropbox-admin\dbadmin\dbadmin_service.py", line 63, in list_all_shared_folders
    self.save_shared_folder_to_cache()
TypeError: save_shared_folder_to_cache() takes exactly 1 argument (0 given)
```

**Comment by lijamie98** [comment]
Fixed.
